### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by ahmetseha** [Kodluyoruz/taskforce#211]
![İlk-Web-Sayfamız](https://user-images.githubusercontent.com/45859293/104202278-c3d12780-543b-11eb-9ed1-a638d880b5d1.png)

**Comment by ramazansancar** [comment]
Ekleme yapıldı. Teşekkürler :)

**Comment by ahmetseha** [comment]
Rica ederim :)

Ramazan SANCAR <notifications@github.com>, 19 Oca 2021 Sal, 04:51 tarihinde
şunu yazdı:
