### ISSUE TITLE
İssue (Low Priorty) Patika.dev Front-End eğitimi Git eğitimi bulunamayan sayfa

### ISSUE THREAD

**Issue by laf1010** [Kodluyoruz/taskforce#531]
Patika.dev sitesindeki Front-End eğitiminin altında bulunan Git bölümünde verilen linkte içerik bulunamadı hatası.

Oluşturma adımları ;
1. Patika.dev sitesine gir ve eğitimler isimli başlığa tıkla
2. Frontend Web Development Patikasına tıkla
3. "GIT" isimli eğitime giriş yap
4. "Markdown Nedir ? - 2 Ders " isimli Pencereyi aç ve "Ödev 1" isimli derse tıkla
5.  En altta bulunan " Örnek Readme Dosyası" başlığındaki linke tıkla.

İlgili Sayfa Linki : https://www.patika.dev/egitimler/ogren/git/ornekreadme.md

**Comment by cengizcmataraci** [comment]
> Patika.dev sitesindeki Front-End eğitiminin altında bulunan Git bölümünde verilen linkte içerik bulunamadı hatası.
> 
> Oluşturma adımları ;
> 
> 1. Patika.dev sitesine gir ve eğitimler isimli başlığa tıkla
> 2. Frontend Web Development Patikasına tıkla
> 3. "GIT" isimli eğitime giriş yap
> 4. "Markdown Nedir ? - 2 Ders " isimli Pencereyi aç ve "Ödev 1" isimli derse tıkla
> 5. En altta bulunan " Örnek Readme Dosyası" başlığındaki linke tıkla.
> 
> İlgili Sayfa Linki : https://www.patika.dev/egitimler/ogren/git/ornekreadme.md

Selam, linki düzenledim şu an erişim sağlayabilirsin. Kolay gelsin.
