### ISSUE TITLE
bootstrap odev1 açılmıyor

### ISSUE THREAD

**Issue by Rotarymoon** [Kodluyoruz/taskforce#571]
https://app.patika.dev/moduller/bootstrap/odev1 linkte bootstrapın eğitim içeriği sayfası açık kalıyor, ödev sayfası açılmıyor.

**Comment by osman-akdag** [comment]
Bende bootstrap odev1 e ulaşamadım.

**Comment by bedirhannbayrak** [comment]
bende de aynı şekilde

**Comment by osman-akdag** [comment]
Düzelmiş kontrol edin isterseniz
