### ISSUE TITLE
Git eğitiminin ödev1 linki çalışmıyor.

### ISSUE THREAD

**Issue by metehanbolatt** [Kodluyoruz/taskforce#573]
GIT eğitimini tamamladıktan sonra gösterilen ödev 1 linkine tıklayınca sayfa herhangi bir dönüş yapmıyor.

**Comment by aksolip** [comment]
Aynı hatayı bende almaktayım

**Comment by TugceAras** [comment]
Bende de ödev1 'e basınca herhangi bir şey olmuyor. Nasıl açacağız ödev1' i ?

**Comment by rahmikse** [comment]
Aynı hatayı alıyorum . Çözüme kavuşturulmadı sanırım.

**Comment by TugceAras** [comment]
Sizde de git eğitimi %90 da mı kaldı? %100 olmuyor sanırım ödev açılmadığından.

**Comment by rahmikse** [comment]
Evet %90 tamamlandı olarak görünüyor. Bir geri bildirim emaili attım. Dönüş yapılırsa bilgilendirme yaparım. İyi çalışmalar.

**Comment by TugceAras** [comment]
Bilgilendirme çok iyi olur teşekkürler. İyi çalışmalar.
